The following notebook supports the lecture on cryptography. The code is not designed to deliver optimal performance, but rather to illustrate the concepts in the clearest way. Minimal optimization has been done, with the exception of exponentiation as it could cause overflow errors. 

This notebook can be redistributed, adapted or copied freely, though the author should be acknowledged. This document may still contain typo’s / mistakes, and as such comments are welcome. Contact information can be found on the author’s website.

Seppe Staelens

In [2]:
import numpy as np

## Initial example

The linking matrix

In [3]:
L = np.array([[0, 1/3, 1/3, 1/3], 
              [1/2, 0, 0, 1/2], 
              [0, 0, 0, 1],
              [0, 1/2, 1/2, 0]]).T
print(L)

[[0.         0.5        0.         0.        ]
 [0.33333333 0.         0.         0.5       ]
 [0.33333333 0.         0.         0.5       ]
 [0.33333333 0.5        1.         0.        ]]


Initial guess

In [4]:
v = np.array([[1/4, 1/4, 1/4, 1/4]]).T
print(v)

[[0.25]
 [0.25]
 [0.25]
 [0.25]]


The power iteration procedure

In [5]:
def power_iteration(L, v, num_simulations):
    for i in range(num_simulations):
        v = L@v
    return v

In [6]:
print(power_iteration(L, v, 1))
print(power_iteration(L, v, 10))
print(power_iteration(L, v, 100))
print(power_iteration(L, v, 1000))

[[0.125     ]
 [0.20833333]
 [0.20833333]
 [0.45833333]]
[[0.11208064]
 [0.25438549]
 [0.25438549]
 [0.37914838]]
[[0.11999863]
 [0.24000249]
 [0.24000249]
 [0.39999639]]
[[0.12]
 [0.24]
 [0.24]
 [0.4 ]]


So, the eigenvector with eigenvalue 1 is $v = \begin{pmatrix} 0.12 \\ 0.24 \\ 0.24 \\ 0.4 \end{pmatrix}$

Another initial value

In [7]:
v2 = np.array([[1, 2, 3, 20]]).T
v2 = v2/np.sum(v2)

In [8]:
power_iteration(L, v2, 1000)

array([[0.12],
       [0.24],
       [0.24],
       [0.4 ]])

## Adding traps

### Spider trap

In [9]:
L2 = np.array([[0., 0.5, 0., 0.],
              [0.5, 0.5, 0., 0.],
              [0.5, 0., 1., 0.],
              [0., 0., 0., 1.]])
print(L2)

[[0.  0.5 0.  0. ]
 [0.5 0.5 0.  0. ]
 [0.5 0.  1.  0. ]
 [0.  0.  0.  1. ]]


In [11]:
power_iteration(L2, v, 1000)

array([[1.64091934e-93],
       [2.65506326e-93],
       [7.50000000e-01],
       [2.50000000e-01]])

This clearly tends towards $\begin{pmatrix} 0 \\ 0 \\ 1\end{pmatrix}$

### Dead end

In [71]:
L3 = np.array([[0.5, 0.5, 0],
              [0.5, 0, 0.],
              [0., 0.5, 0.]])
print(L3)

v3 = np.array([[1/3, 1/3, 1/3]]).T

print("\n", v3)

[[0.5 0.5 0. ]
 [0.5 0.  0. ]
 [0.  0.5 0. ]]

 [[0.33333333]
 [0.33333333]
 [0.33333333]]


In [75]:
power_iteration(L3, v3, 1000)

array([[3.54008435e-93],
       [2.18789245e-93],
       [1.35219190e-93]])

This clearly tends towards $\begin{pmatrix} 0 \\ 0 \\ 0\end{pmatrix}$

### Solution

In [89]:
def adjusted_power_iteration(L, v, num_simulations, alpha):
    dims = v.shape
    dim = dims[0]
    for i in range(num_simulations):
        v = alpha*L@v + (1-alpha)*np.ones(dims)/dim
    return v

In [91]:
adjusted_power_iteration(L2, v3, 10000, 0.8)

array([[0.21212121],
       [0.15151515],
       [0.63636364]])